image: docker:18.09.7

variables:
    VERSION: "1.1"
    CI_REGISTRY: "gitlab.rc.uab.edu:4567"
    DOCKER_URL: "$CI_REGISTRY/ccts-informatics-pipelines/dvctools:$VERSION"

services:
    - docker:18.09.7-dind

before_script:
    - docker info
    - echo $VERSION
    - echo $CI_REGISTRY
    - echo $DOCKER_URL
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD

build_image:
    stage: build
    script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_URL .
    - docker push $DOCKER_URL

test:
    stage: test
    image: $DOCKER_URL
    script:
    - python3.6 -m unittest discover -p "*_test.py"
