image: docker:18.09.7

variables:
    VERSION: "1.1"
#    CI_REGISTRY: "gitlab.rc.uab.edu:4567"
#    DOCKER_URL: "$CI_REGISTRY/ccts-informatics-pipelines/dvctools:$VERSION"
    DOCKER_URL: "jelaiw/dvctools:$VERSION"

services:
    - docker:18.09.7-dind

before_script:
    - docker info
    - echo $VERSION
    - echo $DOCKER_URL
    - echo $REGISTRY_USER

build_image:
    stage: build
    script:
#    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin 
    - docker build -t $DOCKER_URL .
    - docker push $DOCKER_URL

test:
    stage: test
    image: $DOCKER_URL
    script:
    - python3.6 -m unittest discover -p "*_test.py"
