image: docker:19.03.12

variables:
    DVCTOOLS_VERSION: "1.8"
    DVCTOOLS_DOCKER_URL: "jelaiw/dvctools:$DVCTOOLS_VERSION"
    DOCKER_TLS_CERTDIR: "/certs"

services:
    - docker:19.03.12-dind

build:
    stage: build
    before_script:
    - docker info
    script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin 
    - docker build -t $DVCTOOLS_DOCKER_URL .
    - docker push $DVCTOOLS_DOCKER_URL

test:
    stage: test
    image: $DVCTOOLS_DOCKER_URL
    script:
    - python3.6 -m unittest discover -p "*_test.py"

deploy:
    stage: deploy
    image: ubuntu:18.04
    # See step 3 at https://docs.gitlab.com/ee/ci/ssh_keys/README.html#ssh-keys-when-using-the-docker-executor for example with comments.
    before_script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'   
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        # See https://www.cyberciti.biz/faq/linux-unix-osx-bsd-ssh-run-command-on-remote-machine-server/.
        - ssh jelaiw@cheaha.rc.uab.edu 'bash -s' < simg-deploy.sh $DVCTOOLS_VERSION $DVCTOOLS_DOCKER_URL
