image: docker:19.03.1

variables:
    VERSION: "1.1"
    CI_REGISTRY: "gitlab.rc.uab.edu:4567"
    DOCKER_URL: "$CI_REGISTRY/ccts-informatics-pipelines/dvctools:$VERSION"

before_script:
    - echo $VERSION
    - echo $CI_REGISTRY
    - echo $DOCKER_URL
    - echo $CI_JOB_TOKEN

build_image:
    stage: build
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $DOCKER_URL .
    - docker push $DOCKER_URL

test:
    stage: test
    image: $DOCKER_URL
    script:
    - python3.6 -m unittest discover -p "*_test.py"
